### ISSUE TITLE
Dealer blackjack condition

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#26]
When the dealer blackjacks, I take it you calculate that when you "deal yourself" the card.

BUT can you at least first let all the players take turns and do their thing, because I have no idea how to deal with not being asked by the dealer for % playerNo turn... I mean, I could totally just put a goto but https://goo.gl/dA2hTy

EDIT (from Bimesh): This is also a problem because the player should still win if they get a blackjack (even if the dealer gets a blackjack).

**Comment by ecnivo** [comment]
I mean, there are really messy ways to resolve this....

**Comment by xuwilliam01** [comment]
The dealer cant possibly blackjack before all of the other player's turns
(because the facedown card is not flipped until the dealer's turn) , so all
turns should be played out anyway. Be careful of the scenario of players
getting blackjack from their first two cards (ace and 10 card) as once it
is time for their turn we dont call their turn but instead just broadcast
that they had a blackjack, which is essentially skipping their turn cause
they won already

**Comment by ecnivo** [comment]
Not true. The server actually broadcasts its cards without even asking the user for their turn and starting a new round, thereby making my code gross.

**Comment by ecnivo** [comment]
![image](https://cloud.githubusercontent.com/assets/10538710/11646278/59866d22-9d2a-11e5-995e-80ea1f7973b4.png)
The server completely skips any client inputs.

**Comment by Bimde** [comment]
Vince is correct, this is a bug, I tested it as well.

**Comment by xuwilliam01** [comment]
Yeah sorry I wasnt aware of the bug. The dealer's hidden card should be
registered after all the player turns when it's finally revealed, as
players should still have a chance to get a blackjack themselves and win
the round

**Comment by Bimde** [comment]
Fixed.

**Comment by ecnivo** [comment]
Not fixed. 
![still not fixed](https://cloud.githubusercontent.com/assets/10538710/11657147/8b65190c-9d88-11e5-901c-43bc6d7ba15f.PNG)

**Comment by pcjl** [comment]
It works.

**Comment by ecnivo** [comment]
Thanks!
